--SELECT * FROM [TerminalMSSQL].[dbo].[CONTACT_DATA];
--SELECT * FROM [TerminalMSSQL].[dbo].[AGENTS];
--SELECT * FROM [TerminalMSSQL].[dbo].[CLIENTS];
--SELECT * FROM [TerminalMSSQL].[dbo].[ACCOUNTS];
--SELECT * FROM [TerminalMSSQL].[dbo].[AIRCRAFT_MODELS];
--SELECT * FROM [TerminalMSSQL].[dbo].[AIRCRAFTS];
--SELECT * FROM [TerminalMSSQL].[dbo].[MAINTENANCE];

--SELECT NAME, ADDRESS1, ADDRESS2, CITY, EMAIL, [LOGIN], [PASSWORD], AC.[PERMISSIONS]
--FROM CONTACT_DATA AS C INNER JOIN AGENTS AS A ON C.CONTACT_DATA_ID = A.CONTACT_DATA_ID
--INNER JOIN ACCOUNTS AS AC ON AC.AGENT_ID = A.AGENT_ID;

--DELETE FROM CONTACT_DATA WHERE NAME = 'Marcin Nowak'

--SELECT NAME, ADDRESS1, ADDRESS2, CITY, EMAIL, [LOGIN], [PASSWORD], AC.[PERMISSIONS]
--FROM CONTACT_DATA AS C INNER JOIN AGENTS AS A ON C.CONTACT_DATA_ID = A.CONTACT_DATA_ID
--INNER JOIN ACCOUNTS AS AC ON AC.AGENT_ID = A.AGENT_ID;

--SELECT * FROM ACCOUNTS;

DECLARE @ret int;
EXEC @ret = [dbo].VALIDATE_CREDENTIALS_FUNCTION @login = 'm.nowak', @hash = 'hash01';
PRINT 'Value:';
PRINT @ret;