CREATE TABLE [dbo].[ACCOUNTS]
(
	[ACCOUNT_ID] INT NOT NULL PRIMARY KEY, 
    [LOGIN] VARCHAR(16) NOT NULL, 
    [PASSWORD] VARCHAR(16) NOT NULL, 
    [PERMISSIONS] TINYINT NOT NULL, 
    [STATUS] TINYINT NOT NULL, 
    [AGENT_ID] INT NULL
)
