CREATE TABLE [dbo].[AIRCRAFT_MODEL]
(
	[AIRCRAFT_MODEL_ID] INT NOT NULL PRIMARY KEY, 
    [TYPE] VARCHAR(8) NOT NULL, 
    [SIZE] VARCHAR(8) NOT NULL, 
    [MODEL_NAME] VARCHAR(8) NULL, 
    [MANUFACTURER] VARCHAR(8) NULL
)
