/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

PRINT N'Granting priveleges on [dbo].[CONTACT_DATA]...';
GRANT UPDATE ON [dbo].[CONTACT_DATA] TO AGENT_DBUSER
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[CONTACT_DATA] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[CONTACT_DATA] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[CLIENTS]...';
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[CLIENTS] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[CLIENTS] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[AGENTS]...';
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[AGENTS] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[AGENTS] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[AIRCRAFTS]...';
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[AIRCRAFTS] TO AGENT_DBUSER
GRANT SELECT ON [dbo].[AIRCRAFTS] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[AIRCRAFTS] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[AIRCRAFT_MODELS]...';
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[AIRCRAFT_MODELS] TO AGENT_DBUSER
GRANT SELECT ON [dbo].[AIRCRAFT_MODELS] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[AIRCRAFT_MODELS] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[ACCOUNTS]...';
GRANT SELECT ON [dbo].[ACCOUNTS] TO AGENT_DBUSER
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[ACCOUNTS] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[ACCOUNTS] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[MAINTENANCE]...';
GRANT SELECT ON [dbo].[MAINTENANCE] TO AGENT_DBUSER
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[MAINTENANCE] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[MAINTENANCE] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[RESERVATIONS]...';
GRANT SELECT ON [dbo].[RESERVATIONS] TO AGENT_DBUSER
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[RESERVATIONS] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[RESERVATIONS] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[INFRASTRUCTURE]...';
GRANT SELECT ON [dbo].[INFRASTRUCTURE] TO AGENT_DBUSER
GRANT DELETE, INSERT, SELECT, UPDATE ON [dbo].[INFRASTRUCTURE] TO EMPLOYEE_DBUSER
GRANT SELECT ON [dbo].[INFRASTRUCTURE] TO MANAGER_DBUSER

PRINT N'Granting priveleges on [dbo].[VALIDATE_CREDENTIALS_FUNCTION]...';
GRANT EXECUTE ON [dbo].[VALIDATE_CREDENTIALS_FUNCTION] TO VALIDATE_CREDENTIALS_DBUSER
